version: 0.3
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing system dependencies"
      - sudo yum update -y
      - sudo yum groupinstall -y "Development Tools"
      - sudo yum install -y libGL mesa-libGL mesa-libGL-devel libgomp alsa-lib-devel ffmpeg

      # Install Leptonica (Required for Tesseract)
      - echo "Downloading and installing Leptonica"
      - curl -L -o leptonica.tar.gz https://github.com/DanBloomberg/leptonica/archive/refs/tags/1.83.1.tar.gz
      - tar -xvzf leptonica.tar.gz
      - cd leptonica-1.83.1
      - ./autogen.sh
      - ./configure --prefix=/usr
      - make -j4
      - sudo make install
      - sudo ldconfig
      - cd ..

      # Install Tesseract
      - echo "Downloading and installing Tesseract"
      - curl -L -o tesseract.tar.gz https://github.com/tesseract-ocr/tesseract/archive/refs/tags/5.3.3.tar.gz
      - tar -xvzf tesseract.tar.gz
      - cd tesseract-5.3.3
      - ./autogen.sh
      - ./configure --prefix=/usr
      - make -j4
      - sudo make install
      - sudo ldconfig
      - cd ..

      # Verify tesseract installation
      - which tesseract
      - tesseract -v

      # Install Python dependencies
      - echo "Installing Python dependencies"
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Pre-build stage - Verifying OpenCV and Tesseract installation"
      - python3 -c "import cv2; print('OpenCV version:', cv2.__version__)"
      - tesseract -v

  build:
    commands:
      - echo "Build phase - Setting Tesseract environment variables"
      - export TESSDATA_PREFIX="/usr/share/tesseract-ocr/4.00/tessdata"
      - echo "TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata" | sudo tee -a /etc/environment

artifacts:
  files:
    - '**/*'
