version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
    - cd /usr
    - ls
#       - echo "Updating system packages"
#       - sudo dnf update -y
#       - echo "Installing required dependencies for Tesseract"
#       - sudo dnf install -y gcc gcc-c++ autoconf automake libtool libpng-devel libjpeg-devel libtiff-devel libwebp-devel      
#       - sudo dnf install -y gcc libpng-devel libjpeg-devel libtiff-devel libwebp-devel 
#       # Clean old downloads
#       - echo "Cleaning any old source files"
#       - rm -rf leptonica-* tesseract-* leptonica.tar.gz tesseract.tar.gz
#       # Download and build Leptonica from source
#       - echo "Downloading and installing Leptonica"
#       - curl -L -o leptonica.tar.gz https://github.com/DanBloomberg/leptonica/archive/refs/tags/1.83.1.tar.gz
#       - tar -xvzf leptonica.tar.gz
#       - cd leptonica-1.83.1
#       - ./autogen.sh
#       - ./configure --prefix=/usr
#       - make -j4
#       - sudo make install
#       - sudo ldconfig
# # Check if Leptonica is installed
#       - ldconfig -p | grep lept
#       - cd ..      
#       - echo "Installing Tesseract"
#       #Download and build Tesseract from source
#       - echo "Downloading and installing Tesseract"
#       - curl -L -o tesseract.tar.gz https://github.com/tesseract-ocr/tesseract/archive/refs/tags/5.3.3.tar.gz
#       - tar -xvzf tesseract.tar.gz
#       - cd tesseract-5.3.3
#       - ./autogen.sh
#       - ./configure --prefix=/usr
#       - make -j4
#       - sudo make install
#       - sudo ldconfig
#       # - cd ..
      

      
  pre_build:
    commands:
      - echo "PRE-Build stage"
      - echo "pre build stage completed - PyLint Completed!!"      

  build:
    commands:
      - echo "Post-build phase - verifying Tesseract installation"
      - tesseract -v
      - pip install -r requirements.txt

artifacts:
  files:
    - '**/*'
